name: "🧪 unit-test"
on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: 🧪 unit-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
    - name: Install react
      run: yarn add react@18.2.0
    - name: Install react-native
      run: yarn add react-native@0.72.3
    - name: Install dependencies
      run: yarn install -D
    - name: Test
      run: yarn test