name: "🧪 unit-test"
on:
 push:

jobs:
  release:
    name: 🧪 unit-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: yarn test
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}